server:
  port: 8010

spring:
  application:
    name: ms-identity
  datasource:
    url: jdbc:postgresql://localhost:5432/bd_banking
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # URL del servidor Eureka
    register-with-eureka: true # Indica que este servicio se registre en Eureka
    fetch-registry: true # Habilita la búsqueda de otros servicios en Eureka
  instance:
    prefer-ip-address: true # Usa la IP en lugar del hostname para el registro