version: '1.0' # Iniciar con docker-compose up --build -d

services:
  ms-banking:
    build: ./ms-banking
    ports:
      - "8020:8020"
    depends_on:
      - ms-eureka
    networks:
      - bancopichincha_network

  ms-identity:
    build: ./ms-identity
    ports:
      - "8010:8010"
    depends_on:
      - ms-eureka
    networks:
      - bancopichincha_network

  ms-eureka:
    build: ./ms-eureka
    ports:
      - "8761:8761"
    depends_on:
      - postgres
    networks:
      - bancopichincha_network

  ms-gateway:
    build: ./ms-gateway
    ports:
      - "8080:8080"
    depends_on:
      - ms-eureka
      - ms-identity
      - ms-banking
    networks:
      - bancopichincha_network

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bd_banking
    networks:
      - bancopichincha_network
    volumes:
      - ./schema_banking.sql:/docker-entrypoint-initdb.d/schema_banking.sql

networks:
  bancopichincha_network:
    driver: bridge